### PR TITLE
use Fira without ligatures for more beginner-friendliness

### LINKED ISSUE #12: Ligature fonts on the rOpenSci website
Recently, the rOpenSci website changed to ligatured FiraCode. I believe that using ligatures in this setting is not the right choice. 

Ligatures are cool but confusing to newcomers. The fact of the matter is that R does not use them; it uses characters from the keyboard. Since it's not actually R, someone less familiar with the language is going to be confused about what they are and how to make them. I realize that they copy and paste fine, but I think that in this setting, it should be clear how it connects to the software you just managed to install on your machine.

FiraCode is very pretty, but beauty should never be more important than accessibility, at least not for an organization like rOpenSci. FiraCode has a non-ligatured version, and I think it would be good to consider that, instead.

(And for the record, this is not any sort of opinion about whether you should or should not use ligatures in general... I don't even really have an opinion about that!)

### PR DESCRIPTION
**Pull request by maelle**
Fix #12

I found the arguments in #12 interesting (somehow the font might be better fitted for a local editor setting), and was reminded of this by https://twitter.com/DrMowinckels/status/1395325831510216705

### CODE REVIEW

**Comment by maelle** [comment]
Example https://deploy-preview-207--ropensci.netlify.app/blog/2021/02/09/coder/

To me it looks fine. I think the ligatures could become even more puzzling with R native pipe.

**Comment by maelle** [comment]
Related roweb3-styles PR https://github.com/ropensci-org/roweb3-styles/pull/4

**Comment by jeroen** [comment]
I don't have a strong preference either way.

**Comment by mpadge** [comment]
Removing ligatures is a good and important idea, and that looks great!

**Comment by noamross** [comment]
Agree that fewer ligatures in code is better.

**Comment by karthik** [comment]
Also agree.

**Comment by maelle** [comment]
Thanks all! Enough voices in favor of the change.

**Pull request merged**
