### PR TITLE
bundle targets tech note

### PR DESCRIPTION
**Pull request by maelle**
@wlandau I am trying to put all your tech note files into one folder (so the post is index.Rmd/index.md inside that folder) -- sorry to bother you but consistency will help website maintenance. I think I changed the paths correctly but would you mind having a look?

### CODE REVIEW

**Comment by maelle** [comment]
what worries me is the file that disappeared when I knit? although the preview looks ok?

**Comment by maelle** [comment]
as a side-note, this is an awesome & exciting post & work!

**Comment by wlandau** [comment]
> what worries me is the files that disappeared when I knit?

Looks like most of those files are resources for the `visNetwork` widgets. The HTML files are still there, so maybe they are self-contained now?

> although the preview looks ok?

The only issue I see is that the `visNetwork` graphs are missing. When I first wrote the tech note, it was difficult to hunt for the right path. That's why I had `../../../../2021-02-03-targets/` in front of those paths.

> as a side-note, this is an awesome & exciting post & work!

Thanks!

**Comment by maelle** [comment]
oooh the visNetwork graphs were in my local preview, let me investigate this! Sorry!

**Comment by wlandau** [comment]
> The only issue I see is that the visNetwork graphs are missing. When I first wrote the tech note, it was difficult to hunt for the right path. That's why I had ../../../../2021-02-03-targets/ in front of those paths.

After inspecting the source of the preview, I think you have the right path. Maybe those deleted files matter after all? Looks like the widget HTML is in the correct place but the external resources are missing.

**Comment by maelle** [comment]
How did you knit your file? I use the RStudio knit button.

**Comment by maelle** [comment]
by default it seems `visSave()` creates self-contained files.

**Comment by wlandau-lilly** [comment]
> How did you knit your file? I use the RStudio knit button.

So did I. 

> by default it seems visSave() creates self-contained files.

I had trouble getting that to work. Maybe we were using different versions of `visNetwork`? Does the local `graph-minimal.html` file render correctly in a browser for you?

**Comment by wlandau** [comment]
> How did you knit your file? I use the RStudio knit button.

So did I. 

> by default it seems visSave() creates self-contained files.

I had trouble getting that to work. Maybe we were using different versions of `visNetwork`? Does the local `graph-minimal.html` file render correctly in a browser for you?

**Comment by maelle** [comment]
I updated visNetwork but the files still didn't appear. It'd be nice if they weren't needed.

Locally yes if I open the HTML files it renders well. :open_mouth:

**Comment by maelle** [comment]
aaah I found the problem https://community.netlify.com/t/dealing-with-changes-to-script-tags/486

**Comment by maelle** [comment]
@wlandau now the iframes work, is there any remaining issue? :slightly_smiling_face: 
Thanks for your patience :sweat_smile:

**Comment by wlandau** [comment]
Looks great to me. I will follow the new structure next time I write a technote.

**Comment by maelle** [comment]
hey no problem at all, there are so many instructions! thanks for helping me bundle it!

**Pull request merged**
