### PR TITLE
add author profile

### PR DESCRIPTION
**Pull request by paocorrales**
I'm not sure how the profile picture works... but I've followed the instructions :see_no_evil:

### CODE REVIEW

**Comment by steffilazerte** [comment]
Looks good to me!
@yabellini, do we have this for something specific?

**Comment by yabellini** [comment]
For the Multilingual Webpage, Pao will be listed as part of the team.  But we need to wait to publish that page for some grant information. 
(and when she write some blog post, we can also use this profile;-))

**Comment by steffilazerte** [comment]
Okay great, I think we can merge this in then, right? @maelle any reason to wait?

**Comment by maelle** [comment]
I think it's fine to merge, indeed.

**Pull request merged**
