### PR TITLE
change images

### PR DESCRIPTION
**Pull request by maelle**
@karthik

### CODE REVIEW

**Comment by karthik** [comment]
@maelle I added the other two images. Let me know if things are ok.

**Comment by maelle** [comment]
@karthik Thanks. I added all illustrations. Is the text in alt ok?

Previews

* bottom of https://deploy-preview-145--ropensci.netlify.app/
image
* top of https://deploy-preview-145--ropensci.netlify.app/community/, try wide and narrow screen
image
image
* bottom of https://deploy-preview-145--ropensci.netlify.app/community/
image

**Comment by maelle** [comment]
@karthik feel free to merge if the previews & alt text are ok.

**Comment by karthik** [comment]
LGTM. :shipit:

**Pull request merged**
