### PR TITLE
custom twitter card

### LINKED ISSUE #20: More parameterizable Twitter share button
@noamross' idea on the standup call.

Make text in tweet intent URL depend on a parameter in posts' metadata.

A fallback could be is that even without the field, it includes author handles from author data

### PR DESCRIPTION
**Pull request by maelle**
Fix #20 

Except there's no fallback on Twitter usernames in params, just a text one would enter.

### CODE REVIEW

**Comment by maelle** [comment]
The reason for not falling back on Twitter usernames from author metadata is that it'd be more complicated to implement without it being super useful as we'd probably even not want the behavior for staff posts. But I suppose I could be convinced otherwise.

In any case if we end up adopting this new field it needs to be documented in the blog guide.

**Comment by steffilazerte** [comment]
I think this would be great! I've opened an issue in the blog guide so I'll remember to document it if/when this goes live.

Also could this be added to the blogdown template, even as an commented out option? I think that would be in roblog3... right?

**Comment by maelle** [comment]
@steffilazerte added to the archetypes, but the wording might be clarified I suppose.

**Comment by steffilazerte** [comment]
I think it's fine, we can add more detail to the blog guide

**Comment by maelle** [comment]
so can I merge this?

**Comment by maelle** [comment]
(or you can)

**Pull request merged**
