### PR TITLE
new-editors-2024

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Comment by mpadge** [comment]
@beatrizmilz @margaretsiple-noaa This is the draft pull request for the blog post introducing you as our new editors. Feel free to comment or tweak any aspects you like. We ask for a written statement from both of you here approving this PR before we publish. Thanks both for everything leading up to and beyond this public announcement!

**Comment by beatrizmilz** [comment]
Hi Mark! 
Thank you!
Can we update the picture for this one?
bea-cropped

**Review by beatrizmilz — COMMENTED** [review]
extra space

**Comment by mpadge** [comment]
@beatrizmilz :

> Hi Mark! Thank you! Can we update the picture for this one?

Sure can, but it would be even better if you could PR that yourself, to https://github.com/ropensci/roweb3/blob/main/themes/ropensci/static/img/team/beatriz-milz.jpeg. That will then add you directly as a public contributor to our website, which we encourage and prefer, if that's okay with you?

**Comment by beatrizmilz** [comment]
> @beatrizmilz :
> 
> > Hi Mark! Thank you! Can we update the picture for this one?
> 
> Sure can, but it would be even better if you could PR that yourself, to https://github.com/ropensci/roweb3/blob/main/themes/ropensci/static/img/team/beatriz-milz.jpeg. That will then add you directly as a public contributor to our website, which we encourage and prefer, if that's okay with you?

Sure! Thank you!

**Comment by MargaretSiple-NOAA** [comment]
This looks good to me! I approve. Thank you Mark and let me know if you need anything else.

**Comment by mpadge** [comment]
@maelle This is now ready for your review and approval. Date is currently Wed 3rd July; shall we move forward and publish sooner? Today?

**Comment by maelle** [comment]
I'll let @yabellini @steffilazerte decide :grin:

**Comment by yabellini** [comment]
Ok, for me to publish when you think it is ready.  Thanks for asking 😄

**Comment by mpadge** [comment]
Thanks @yabellini, i asked @maelle to approve, but she hasn't responded - I guess maybe not working today? It's finished from my side, but somebody should review and approve first; can you do that? You could also then just merge yourself if you want?

**Comment by yabellini** [comment]
I can take care of that.

**Review by maelle — APPROVED** [review]

**Comment by mpadge** [comment]
Thanks both! @yabellini Will you then take care of social stuff? Or @steffilazerte? Either way, please make sure to let @beatrizmilz and @MargaretSiple-NOAA know so they can share the exciting developments!!

**Comment by yabellini** [comment]
Done!

**Comment by mpadge** [comment]
Thank you!

**Pull request merged**
