### PR TITLE
Zebulun-Ghozayel blog skeleton

### PR DESCRIPTION
**Pull request by yabellini**

### CODE REVIEW

**Comment by yabellini** [comment]
Hi  @Ghozayel and @arendsee, this is the draft of your intro blog post.  Please let me know if you want to do some changes.  If you can't review this PR, comment with the changes here and I will apply them.

**Review by arendsee — APPROVED** [review]
Looks good! Thanks for setting this up.

**Comment by yabellini** [comment]
@steffilazerte this is ready for your review. Thanks!

**Review by steffilazerte — COMMENTED** [review]
Hi @yabellini, 

Generally looks good, as usual 😁 . Still need author files and if this is the last introduction, I've added some suggestions to clarify that. See what you think!

* [X] post follows Content Guidelines
* [X] post follows Style Guide
* [X] title is in Title Case
* [X] publication date is ok
* [X] alternative text of images is informative
* [ ] author metadata is provided with correct folder name => **Need author files**
* [X] html not included in pull request of Rmd post
* [X] I ran `roblog::ro_lint_md()` on index.md
* [X] I ran `roblog::ro_check_urls()` on index.md
* [X] I ran a spell-check on index.md
* [X] YAML subject tags are ok ("tech notes" for tech notes; "community" for non-staff non-editor)
* [X] YAML field 'preface' is present if necessary

**Pull request merged**
