### PR TITLE
fix: make r-universe link conditional

### LINKED ISSUE #545: Author pages include R-universe even if there is no profile
The author pages all include a link to R-Universe, but sometimes it doesn't go anywhere if the user doesn't have an R-Universe profile...
e.g., https://ropensci.org/author/cynthia-huang/ links to https://cynthiahqy.r-universe.dev/ which doesn't exist.

### PR DESCRIPTION
**Pull request by maelle**
Fix #545

### CODE REVIEW

**Comment by maelle** [comment]
@jeroen this is for author pages. If there's a GitHub handle, I make a request to the corresponding  R-universe URL and if it exists, it will be shown on the page. This might be a bit inefficient: is there an API point with the list of all universes? This way I could simply look whether the GitHub handle is in that list (and I'd cache the request to that list, well Hugo would do it automatically https://gohugo.io/hugo-pipes/introduction/#error-handling)

**Comment by jeroen** [comment]
There are a few endpoints to get data from all universes, but perhaps those are difficult to parse in hugo?

```r
df=jsonlite::stream_in(url('https://r-universe.dev/stats/universes'))
```

I can also add a new endpoint with just the information we need

**Comment by jeroen** [comment]
I think we actually do need the maintainer list in this case, because maintainers also get an r-universe page though cross referencing the packages they maintain in other universes (even if they don't have their own universe).

> We need a list of existing universes (even those that are not of maintainers, but of organizations), so we can compare the GitHub username (or even the universe name the person lists) to it. 

Do we have people on ropensci that are an organization? 🤔

**Comment by maelle** [comment]
In an author page, you can choose to add an r-universe link, and I was imagining some folks might want to list not their own but an organizational one.

**Comment by jeroen** [comment]
Does this API work?

```sh
# All maintainers in a universe
https://ropensci.r-universe.dev/stats/everyone

# All users and maintainers 
https://r-universe.dev/stats/everyone
```

**Pull request merged**
