### PR TITLE
targets call for contributions

### PR DESCRIPTION
**Pull request by maelle**
@wlandau here's the PR to review, thank you! :pray: 

The publication date is flexible.

### CODE REVIEW

**Comment by wlandau** [comment]
Thank you for your advocacy, @maelle! This post will be incredibly helpful. 

One thing that just occurred to me is that I am increasingly encouraging discussion threads in all my repos, especially for user questions. Would it be okay to include the discussion links for all the repos? Maybe something like this table?

Package | Issue tracker | Discussion forum
---|---|---
[`targets`](https://docs.ropensci.org/targets) | [targets/issues](https://github.com/ropensci/targets/issues) | [targets/discussions](https://github.com/ropensci/targets/discussions)
[`tarchetypes`](https://docs.ropensci.org/tarchetypes) | [tarchetypes/issues](https://github.com/ropensci/tarchetypes/issues) | [tarchetypes/discussions](https://github.com/ropensci/tarchetypes/discussions)
[`gittargets`](https://docs.ropensci.org/gittargets) | [gittargets/issues](https://github.com/ropensci/gittargets/issues) | [gittargets/discussions](https://github.com/ropensci/gittargets/discussions)
[`stantargets`](https://docs.ropensci.org/stantargets) | [stantargets/issues](https://github.com/ropensci/stantargets/issues) | [stantargets/discussions](https://github.com/ropensci/stantargets/discussions)
[`jagstargets`](https://docs.ropensci.org/jagstargets) | [jagstargets/issues](https://github.com/ropensci/jagstargets/issues) | [jagstargets/discussions](https://github.com/ropensci/jagstargets/discussions)

**Comment by maelle** [comment]
@wlandau I added the table, what a good idea!
Can you please comment on the TODO in the text (I wonder if we should clarify what a path would be from one-time question answerer to "forum curators") and tell me whether further tweaks are needed?

**Comment by wlandau** [comment]
GitHub triage access is a great idea for potential moderators, I had not thought of that. If anyone spends a lot of time answering questions or if throughput increases even more, I may initiate those conversations one-on-one. I think the number of potential moderators is small enough for that.

For the post, I think it would be nice to simply ask for thoughts and comments on issues and discussions. This is something people can do casually without the responsibility of elevated access, and it is by far the most helpful kind of contribution.

**Comment by maelle** [comment]
Ok! I plan a publication one week from now, does the post look good?

**Comment by wlandau** [comment]
Fantastic @maelle, thank you so much!

**Pull request merged**
