### PR TITLE
Polarverse blog post translated to Portuguese

### PR DESCRIPTION
**Pull request by yabellini**
The blog post was cross-posted with LatinR (as we talked), and @beatrizmilz translated to Portuguese.  I'm adding that version here to our web blog. 
I also added the editor YAML field: Steffi for English, Yani for Spanish and Bea for Portuguese.

### CODE REVIEW

**Comment by yabellini** [comment]
@maelle, I need your support on this one.  I added a new index for the Portuguese version of this blog post, but the language is not shown on the right panel when English and Spanish are shown.  What should I do to list the language?

**Comment by maelle** [comment]
@yabellini looking at https://github.com/ropensci/roweb3/commit/df916febdf09397407fb455b094d966ad58c9a2d#diff-dac9f513e988b7d56b732b2ba6e52ab6c92706035815bdb05da0fb66d1697b4a

- editing the config (I just did that in a commit)
- maybe also needed: adding archive/_index.pt.md ...

**Comment by maelle** [comment]
https://deploy-preview-831--ropensci.netlify.app/pt/blog/2023/12/05/2023-12-05-divide-y-venceras-de-polar-al-polarverse/

**Comment by beatrizmilz** [comment]
Thank you Yani and Maelle!

**Pull request merged**
