### PR TITLE
Tables

### LINKED ISSUE #27: Improve styling of tables
The packages table on https://ropensci.org/blog/2020/05/19/covid-19-open-data/ looks pretty bad. It only shows a small part of the table and it isn't obvious that it is scrollable? 

In the old site we displayed the full table: https://roweb2.netlify.app/blog/2020/05/19/covid-19-open-data/

Bootstrap 4 (which we use) has many built-in options to style tables: https://getbootstrap.com/docs/4.0/content/tables/

### PR DESCRIPTION
**Pull request by maelle**
Fix #27

### CODE REVIEW

**Comment by maelle** [comment]
Now, horizontal scrolling is still not good?!!

**Comment by maelle** [comment]
I mean, the scrollbar is at the bottom and you can't see it. adding a second scrollbar is not fun which is why I had added a maximal height. Would appreciate suggestions!

**Comment by maelle** [comment]
:wave: @jeroen

**Comment by jeroen** [comment]
I see the css has changed, but not the pcss sources?

**Comment by maelle** [comment]
because the rules only lived in a css to begin with? https://github.com/ropensci-org/roweb3-styles/pull/2

**Comment by maelle** [comment]
:wave: @jeroen

**Comment by jeroen** [comment]
It's definitely an improvement, but still doesn't fit well on the page. 

Would it be possible to try to reduce the font size a bit for table text, and perhaps decrease the padding for cells?  Currently we have `.table td{padding 0.75rem}` but maybe `0.5rem` is enough? And perhaps add `.table {font-size: 1rem;}` so that the text in the table is "normal" size instead of paragraph-text size.

Sorry for being such a pain

**Comment by maelle** [comment]
"Sorry for being such a pain", no that's what reviewers are for, giving constructive feedback! Thanks, I'll try to get to this soon.

**Comment by maelle** [comment]
@jeroen I've update this PR and https://github.com/ropensci-org/roweb3-styles/pull/2

**Comment by maelle** [comment]
reg the conflict, once you agree with the style I'll solve the conflict by merging the roweb3-styles PR and running npm run build there.

**Comment by jeroen** [comment]
Thanks it looks much better now!

Hmm how did the conflict appear? Did we have other style changes in the mean time? Perhaps it would be safest to start a new PR with these changes on top of the latest master?

**Comment by maelle** [comment]
All CSS changes are also in roweb3-styles, which is why I'll re-generate a css file from there.

**Pull request merged**
