### PR TITLE
Create 2020-11-11-killick-nhsr.md

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@maelle I didn't create an author page for Rebecca Killick (stats peer review board member) but the [preview still looks fine](https://deploy-preview-92--ropensci.netlify.app/talks-papers/). This talk is in the past.

```
attendees:
  - Jane Doe # each attendee needs an author page
```

**Comment by maelle** [comment]
you are right, the author page is only needed if the event is in the future. I hadn't envisioned this case. :sweat_smile:

**Comment by maelle** [comment]
I'll add an author page because of the existence of https://deploy-preview-92--ropensci.netlify.app/events/nhsrconf2020/

**Comment by maelle** [comment]
I'll let you review the author page (you might want to add a bio).

**Comment by maelle** [comment]
Actually I'll merge, I'm sure enough it's ok.

**Comment by stefaniebutland** [comment]
wonderful thank you @maelle !!

**Pull request merged**
