### PR TITLE
Samples of DOI inclusion

### PR DESCRIPTION
**Pull request by maelle**
https://deploy-preview-632--ropensci.netlify.app/blog/2023/08/25/news-august-2023/

### CODE REVIEW

**Comment by karthik** [comment]
Is this just an example DOI?

CleanShot 2023-09-05 at 08 49 44@2x

Can we make the icon a copy icon so people can copy the DOI into their clipboard?
Can we

**Comment by mfenner** [comment]
You could integrate with DOI content negotiation for other options, e.g.a bibtex or formatted citation link. And you should make sure Zotero understands your page and detects the DOI. Let me know if you need something from Rogue Scholar.

**Comment by maelle** [comment]
@mfenner 

> You could integrate with DOI content negotiation for other options, e.g.a bibtex or formatted citation link. And you should make sure Zotero understands your page and detects the DOI. 

I'm not sure I follow. You mean also offering readers a way to copy-paste the citation already formatted?

Another question. How would the rOpenSci website best access information on a DOI
- registering the DOI in each post's YAML metadata but in that case when will we know a DOI has been minted for a new post?
- does Rogue Scholar have an API we could query at build time to add the DOI for each post based on their relative URL?
- in both cases, what could be a fallback URL for "rOpenSci on Rogue Scholar" that we could display when we can't find a DOI?
Thank you :pray:

**Comment by maelle** [comment]
@karthik I started experimenting a bit with a copy-paste button, but I wonder whether it's worth adding a JS library (thoughts/tips @jeroen?)

**Comment by mfenner** [comment]
You can use Crossref DOI content negotiation to get Rogue Scholar DOIs for blog posts as bibtex or formatted citation. I have integrated functionality [here](https://rogue-scholar.org/posts), but you could do the same on the rOpenSci blog.

**Comment by mfenner** [comment]
DOIs for Rogue Scholar posts are randomly generated when posts are registered with Crossref. This functionality has a long history that I can explain if there is interest, but this means that I don't know the DOI in advance. One advantage is that there is no confusion with DOI-like strings (that look like DOIs but are not registered and don't resolve to anything), but the challenge is to tell rOpenSci about the DOI after it has been registered. More background also in my blog post from today: https://doi.org/10.53731/gvb08-7kc16

**Comment by maelle** [comment]
@mfenner when I click on bibtex onhttps://rogue-scholar.org/posts I get "Metadata not found". But now I understand the idea!

**Comment by maelle** [comment]
@mfenner is there a JSON produced for instance, of blog post URLs together with the DOI? I could consult this at build time, and for posts that do not have a match (yet), point to say https://rogue-scholar.org/blogs/ropensci?

**Comment by mfenner** [comment]
@maelle maybe you tried one of the blog posts from this morning. There is a delay of a few hours (up to 24 hours and sometimes more) before the Crossref API is updated and content negotiation works.

**Comment by mfenner** [comment]
@maelle there is a JSON API for the rOpenSci blog at https://rogue-scholar.org/api/blogs/e22ws68. I plan to refactor it in October to use Python instead of Javascript to address a few important shortcomings.

**Comment by karthik** [comment]
Looks good Maëlle! Thank you.
One change. Right now if I copy, it also copies the word Cite.
So I get this in my clipboard

```
Citedoi.org/10.59350/zh01g-yby98
```

The Cite needs to be dropped.

**Comment by maelle** [comment]
Note to self: explore https://yihui.org/en/2023/09/copy-button/

**Comment by maelle** [comment]
Note to self: https://www.crossref.org/documentation/retrieve-metadata/content-negotiation/

**Comment by maelle** [comment]
@karthik does the current version look good to you? I think we could add more citation formats later, and go for just this copy-paste button for now.

**Comment by mfenner** [comment]
On Monday I launched a dedicated REST API for Rogue Scholar, written in Python. It currently uses DOI content negotiation for formatted metadata, but I plan to support metadata in various formats natively. https://doi.org/10.53731/ar11b-5ea39

**Comment by maelle** [comment]
@mfenner is something wrong with the API link? https://rogue-scholar.org/api/blogs/e22ws68

**Comment by maelle** [comment]
https://rogue-scholar.org/api/blogs/ropensci doesn't work either

**Comment by mfenner** [comment]
The new API is at https://api.rogue-scholar.org, and no longer at https://rogue-scholar.org/api. (And Python instead of JavaScript.)

**Comment by mfenner** [comment]
The redirects from the old API endpoint don't seem to work, but let me look into this.

**Comment by mfenner** [comment]
@maelle  I fixed the redirect from https://rogue-scholar.org/api to https://api.rogue-scholar.org. https://rogue-scholar.org/api/blogs/ropensci now works again.

**Comment by mfenner** [comment]
The redirect for https://rogue-scholar.org/api/blogs/e22ws68 (to https://api.rogue-scholar.org/blogs/ropensci) is now also fixed.

**Comment by maelle** [comment]
one thing I tested locally: changing the URL to make the API "unavailable" and checking it didn't break the build (the fallback URL was used)

**Pull request merged**
