### PR TITLE
update data/team.json with new editors

### PR DESCRIPTION
**Pull request by mpadge**
@beatrizmilz Apologies for the oversight on our part that you weren't yet included in team data for our main website. On line 453 below is an empty "affiliation" field for you. Please let us know whether you'd like anything in there; if not, it's also okay if it remains empty. Thanks!

### CODE REVIEW

**Review by maelle — APPROVED** [review]

**Comment by beatrizmilz** [comment]
Hi @mpadge ! No problem. 
I applied to a post-doc and got accepted. However, I am not yet officially affiliated because we are waiting for the bureaucratic procedures of the funding agency. After I have a confirmation, I can send a PR to add the information.

Thank you!

**Comment by mpadge** [comment]
Thanks @beatrizmilz. In the meantime, you may enjoy that fact that you appear very first on our list of [smiling editorial faces](https://ropensci.org/software-review/) :wink:

**Comment by beatrizmilz** [comment]
> Thanks @beatrizmilz. In the meantime, you may enjoy that fact that you appear very first on our list of [smiling editorial faces](https://ropensci.org/software-review/) 😉

It is an honor to be on the same list of so many incredible people!

**Comment by maelle** [comment]
Congrats on the post-doc @beatrizmilz (and awesome to have you on board)!

**Comment by beatrizmilz** [comment]
> Joining the conversation to say that I'm so glad you're in this role @beatrizmilz ! 😃

Thank you Yani! I'm honored to be part of the team of editors of rOpenSci!

**Comment by beatrizmilz** [comment]
> Congrats on the post-doc @beatrizmilz (and awesome to have you on board)!

Thank you so much @maelle !

**Pull request merged**
