### PR TITLE
fix generalreview editor alumni list; closes #792

### LINKED ISSUE #792: Past stats editors appear as general alumni
The ["Former editors" on the general software review page](https://ropensci.org/software-review/) includes many who should appear only on the stats page. Entries on the stats page are all okay, and include several who appear because they have roles like these:
https://github.com/ropensci/roweb3/blob/929d31fc00ea2e4cb497bb2bd5bd5e77a2faebdc/data/team/team.json#L404-L406

That all works as it should. The problem arises with entries like these:
https://github.com/ropensci/roweb3/blob/929d31fc00ea2e4cb497bb2bd5bd5e77a2faebdc/data/team/team.json#L378-L382

With `stats: true` and no `generalreview: true`, they should appear on stats page only, and not on the general page. @maelle PR incoming that should fix this...

### PR DESCRIPTION
**Pull request by mpadge**

### CODE REVIEW

**Comment by maelle** [comment]
This currently does not work, does the JSON need to be updated too?

image

**Comment by mpadge** [comment]
> This currently does not work, does the JSON need to be updated too?
> 

I guess so? Let me check ...

**Comment by mpadge** [comment]
There we go:
image

Thanks for catching that!

**Review by maelle — APPROVED** [review]
:rocket:

**Pull request merged**
