### PR TITLE
Move tech notes

### LINKED ISSUE #124: Blog/Technotes display
Perhaps there could be some clarification/tweeking of the main blog page (https://ropensci.org/blog/).

- It's not clear where technotes really are, the "#tech-notes" heading under "Highlights", implies that technotes are blog posts tagged as a technote, but since they're not, they don't actually appear in the "All Posts" section below, so people may not realize they specifically have to click on the "tag".
 
- Readers need to scroll quite a bit to reach the "All Posts" section under the featured cards and highlights section.

I'm not quite sure what kind of solutions to suggest, but for the first option, I actually wouldn't mind moving technotes to blog posts that are tagged #tech-note (not sure what @stefaniebutland thinks of this!).

For the second option, perhaps the Featured Cards could be smaller (there's a fair bit of white space)? Or part of the Highlights? Perhaps the Highlights cards could also be a bit smaller (although not sure how much smaller they can go).

### PR DESCRIPTION
**Pull request by maelle**
Fix #124 

* Script to add the tag

```r
path <- "/home/maelle/Documents/ropensci/roweb3/content/technotes"
modify_tags <- function(tags){
  tags <- as.list(unique(c(tags, "tech notes")))
}

update_yaml_tags <- function(file){
  message(file)
  meta <- rmarkdown::yaml_front_matter(file,
                                       encoding = "utf8")
  tags <- meta$tags
  newtags <- modify_tags(tags)
  
  if(!is.null(tags)){
    if(!all(newtags==tags)){
      file_content <- readLines(file)
      i = grep('^---\\s*$', file_content)
      file_content <- file_content[(i[2]+1):length(file_content)]
      meta$tags <- newtags
      #browser()
      file_content <- c(c("---"),
                        blogdown:::as.yaml(meta),
                        c("---"),
                        file_content)
      writeLines(file_content, file,
                 useBytes = TRUE)
    }
  }
  
}

files <- dir(path, full.names = TRUE, recursive = TRUE)
files <- files[fs::path_ext(files) == "md"]
files <- files[fs::path_file(files) != "_index.md"]
files <- files[fs::path_file(files) != "raw_data_source.md"]

purrr::walk(files, update_yaml_tags)
```

* Create redirects
```r

library("magrittr")
"http://localhost:1313/sitemap.xml" %>%
  xml2::read_xml() %>%
  xml2::xml_ns_strip() %>%
  xml2::xml_find_all("//loc") %>%
  xml2::xml_text() %>%
  stringr::str_remove_all("http://localhost:1313") %>%
  stringr::str_remove("\\/$") -> links
technotes_links <- links[grepl("/technotes/.*", links)]

transform_link <- function(link) {
  cat(link)
  cat(" ")
  cat(sub("technotes", "blog", link))
  cat("\n")
}
purrr::walk(technotes_links, transform_link)
```

* Copy content of technotes folder to blog folder except for "_index.md"
* The layout for the tech notes list page has been updated.

### CODE REVIEW

**Comment by maelle** [comment]
Waiting on #137 to be merged.

**Comment by maelle** [comment]
Not sure why Netlify doesn't build a preview, I see nothing related to this PR in Netlify logs. Maybe it needs to be marked as ready for review.

**Comment by jeroen** [comment]
I think it is safer to use a single redirect:

```
/technotes/*	/blog/:splat
```

**Comment by jeroen** [comment]
I think netlify only builds PR's if you target master, and this pr merges into move-note

**Comment by maelle** [comment]
aaaaaaaaaah good point. I'll change the PR once #137 is merged.

**Comment by maelle** [comment]
will open a new pr

**Pull request closed without merging**
