### PR TITLE
add data about cross-posts

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by mfenner** [comment]
@maelle this is very nice, and very much aligned with my thinking. I would personally prefer `_relationships` over `_crossposts0` (the name used in the Crossref metadata). Crossref relationships cover cross-posts (`isIdenticalTo`), translations, and some other use cases. https://www.crossref.org/documentation/schema-library/markup-guide-metadata-segments/relationships/

**Comment by mfenner** [comment]
My only reservation is that Rogue Scholar has to support a wide variety of science blogs, very few of which have the technical expertise of the rOpenSci team. Therefore I like to also support a way to support this functionality via common patterns in the content. This works also works with RSS and Atom, and when the user can't change the feed format.

Something else I added, even though it is not part of Crossref Relationships, is funding information, using the `HasAward` relation type. Let me know if and when that use case becomes relevant for rOpenSci.

**Comment by maelle** [comment]
> I would personally prefer _relationships over _crossposts0 (the name used in the Crossref metadata). Crossref relationships cover cross-posts (isIdenticalTo), translations, and some other use cases. [crossref.org/documentation/schema-library/markup-guide-metadata-segments/relationships](https://www.crossref.org/documentation/schema-library/markup-guide-metadata-segments/relationships/)

Would it mean using `_relationships0`, `_relationships1` etc? There can be several cross-posts but the custom field cannot be a vector otherwise the validator complains.

> My only reservation is that Rogue Scholar has to support a wide variety of science blogs, very few of which have the technical expertise of the rOpenSci team. Therefore I like to also support a way to support this functionality via common patterns in the content. This works also works with RSS and Atom, and when the user can't change the feed format.

I understand. I can switch back to putting the links somewhere in the content.

Speaking of other blogs, would it make sense for Rogue Scholar to provide a feed template for Hugo, probably not ready to use, but with some explanations of what to tweak?

**Comment by mfenner** [comment]
Hm, I have to take a deeper look into how the JSON Feed metadata can best structured. Multiple cross-posts is obviously very common.

Supporting custom JSON Feed metadata and also providing the information is fine.

I have been thinking for a while now to provide documentation on how to set up a blog with Rogue Scholar. Starting with the most popular blogging platforms and that is currently Wordpress, Ghost, and Hugo. The documentation site is at https://docs.rogue-scholar.org/ at hosted on Github, and pull requests are of course appreciated.

**Comment by mfenner** [comment]
I had a look at the JSON Feed documentation https://www.jsonfeed.org/version/1/#extensions-a-name-extensions-a and some example JSON Feeds, so far found only https://micro.blog/feeds/manton.json using extensions.

For the format I think it should be an array similar to post attachments. Everything else feels like a hack, and the validator can be ignored or updated (I am sure other extensions run into the same limitation).

My proposed format would look something like

```json
{
  "_relationships": [
    {
      "url": "https://ropensci.org/blog/2023/09/15/r-universe-stars-5-en/",
      "title": "R-universe: a new take on R package registries",
      "relation": "isTranslationOf"
    },
    {
      "url": "https://bla-bla.github.io/2021/09/15/r-universe-stars-5/",
      "relation": "isIdenticalTo"
    }
  ]
}
```

**Comment by maelle** [comment]
@mfenner I applied the format, is that better?

A next step for me (tomorrow or later) will be to similarly create and use metadata about translations. Sometimes the English version is the original not, sometimes not (cc @yabellini).

**Comment by maelle** [comment]
I won't even try putting this into the validator, Rogue Data is the validator now :smiling_imp:

**Comment by maelle** [comment]
@mfenner just to be sure, is this format ok as is?

**Comment by mfenner** [comment]
This looks good. Need to see a JSON Feed with the new format to see how I can parse it.

**Pull request merged**
