### PR TITLE
June 2022 news

### LINKED ISSUE #350: Fix use cases script

### PR DESCRIPTION
**Pull request by maelle**
Fix #350

### CODE REVIEW

**Comment by mpadge** [comment]
Package dev corner: https://stat.ethz.ch/pipermail/r-package-devel/2022q2/008193.html. I see no confirmation that CRAN have indeed set `_R_CHECK_DEPENDS_ONLY_ = true`. *But*, if we can somehow confirm that, then this would be an important pkg-devel-:triangular_ruler:  point. [CRAN NEWS](https://cran.r-project.org/doc/manuals/r-release/NEWS.html) only says R4.2 changed it so it can be applied selectively to examples, tests, whatevs, and refers straight to [the *R Internals* Manual](https://cran.r-project.org/doc/manuals/r-release/R-ints.html) which has the following rather cryptic statements:

> _R_CHECK_SUGGESTS_ONLY_
>
>    If set to a true value, running examples, tests and vignettes is done with a temporary library directory populated by all the Depends/Imports/Suggests packages. (As exceptions, packages in a ‘VignetteBuilder’ field are always made available.) Default: false (but true for CRAN submission checks: some of the regular checks use true and some use false).
>
> _R_CHECK_DEPENDS_ONLY_
>
>    As for _R_CHECK_SUGGESTS_ONLY_ but using only Depends/Imports (and the exceptions, including test-suite managers in ‘Suggests’). Default: false

Which kinda leaves the official CRAN statement that "some of [our] checks use true and some use false." Ah, okay, all clear then.

**Comment by mpadge** [comment]
Not directly pkg-devel, but kinda, and one of those cool new mini-features on GitHub that folks might otherwise not see: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/

**Review by mpadge — APPROVED** [review]
Looks great! I kept thinking i'd found minor things, then to pause for a moment to realise, actually, all is fine fine fine. Thank you!

**Comment by maelle** [comment]
Thanks a ton @mpadge!

**Comment by jeroen** [comment]
I'd like to add a tiny pitch on how ingesting CRAN gets us closer to our goal of allowing people to find and assess packages in the R ecosystem.Something like this maybe:

The r-universe infrastructure has been upgraded to automatically track development of all Bioconductor/CRAN packages that are maintained on GitHub, GitLab, or BitBucket. Together with other packages signed up by our users, the system now serves over 10k packages and 10k articles, providing a comprehensive database of the best software that the R ecosystem has to offer.

The r-universe website makes it easy to browse by topic, keyword, author, organization etc, and shows extensive information about each package and its development process. We hope this will make it easier to discover interesting software and get a clear sense of the purpose and quality of the many R packages.

**Pull request merged**
