### PR TITLE
Tweak the blog JSON feed for Rogue Scholar ingestion

### LINKED ISSUE #630: JSON feed fixes for Rogue scholar

### PR DESCRIPTION
**Pull request by maelle**
Fix #630 

https://deploy-preview-631--ropensci.netlify.app/blog/index.json

### CODE REVIEW

**Comment by mfenner** [comment]
I would use JSON Feed 1.1: `{ "version": "https://jsonfeed.org/version/1.1" }`. The main difference is the `authors` property.

**Comment by mfenner** [comment]
You can try `"content_html": "{{ .Content | safeHTML }}"`.

**Comment by mfenner** [comment]
I have trouble parsing the relative url for `img` tags. It is relative to the blog post URL, but could also be relative to the blog URL. I think this makes it hard for feed readers to parse correctly. Absolute URLs would be safer.

**Comment by mfenner** [comment]
I wouldn't include the optional `summary`, because that has to be plain text according to the JSON Feed spec, but (sanitized) HTML is useful for scholarly content and also supported in Crossref metadata. Using `<I>, <b>, <sup>, <sub>` tags for example. And it can be generated from `content_html`.

**Comment by maelle** [comment]
thanks! I'll come back to this later today or next week. :pray:

**Comment by maelle** [comment]
Regarding image links, I'm hoping to find a real Hugo solution, because I'm realizing using a regex is just too fragile.

**Comment by maelle** [comment]
still one regex tweak to go, probably some sort of pesky space character.

**Comment by mfenner** [comment]
I have addressed the image src url issue on my end, see https://rogue-scholar.org/blogs/ropensci. Also now filtering out posts with date_published in the future.

**Comment by maelle** [comment]
The error is coming from some text that was escaped (double quotes) but inside a code block. It's example markdown code in a blog post about Pandoc troubleshooting :sob: I'll investigate further.

**Comment by maelle** [comment]
> I have addressed the image src url issue on my end, see [rogue-scholar.org/blogs/ropensci](https://rogue-scholar.org/blogs/ropensci). Also now filtering out posts with date_published in the future.

Thank you! I think the current feed only has non future posts, that's something I tried tackling at the beginning of the PR.

**Comment by mfenner** [comment]
Removing posts with a future publication date is generally useful (e.g. for other blogs), even if your code handles that.

**Comment by maelle** [comment]
I'll give jsonify and safeJS a new try.

**Comment by maelle** [comment]
@mfenner the feed can be parsed by (at least my) browser! Are there further problems on your end? 

To summarize in case others want to make JSON feeds (Happy to contribute this to the docs if relevant):
- the content needs to have no new line;
- then it can be "jsonified" which will escape what needs to be escaped.

I had tried jsonify when I wasn't removing the new lines yet...

I feel there are few examples of JSON feeds with Hugo and the ones that exist are not full content?

**Comment by maelle** [comment]
https://deploy-preview-631--ropensci.netlify.app/blog/index.json

**Comment by mfenner** [comment]
I have no quick way of checking the feed because I don't have a good staging environment yet. And I don't know whether there is JSON Feed validator around, e.g. using JSON Schema. If the JSON is valid, I can probably consume it, and tweak as needed. Maybe publish at a URL different URL from https://ropensci.org/rbloggers/index.json for more testing.

**Comment by maelle** [comment]
can you use the URL https://deploy-preview-631--ropensci.netlify.app/blog/index.json for testing or does it need to be under ropensci.org?

**Comment by mfenner** [comment]
I can use any URL. When I try to ingest that feed it imports 523 posts. Need to study the data in more detail but it looks good and is super-fast!

**Comment by mfenner** [comment]
The author processing needs some effort on my end, but it is also the first JSON Feed I am properly processing.

**Comment by mfenner** [comment]
You can see the processed feed at https://rogue-scholar.org/blogs/ropensci and for example could try out full-text search.

**Comment by maelle** [comment]
Very nice, thank you!! :smiley: I see https://rogue-scholar.org/blogs/ropensci?page=1&query=pandoc works well :ok_hand:

**Comment by mfenner** [comment]
Or use https://rogue-scholar.org/posts?query=pandoc to query posts from all blogs about Pandoc.

**Comment by maelle** [comment]
@mfenner the feed is now valid according to https://validator.jsonfeed.org/

**Comment by mfenner** [comment]
Excellent. Let me know when the feed goes live on main branch so that I can start registering DOIs (because the blog post URLs will be stable, in contrast to something like https://deploy-preview-631--ropensci.netlify.app/blog/2023/08/25/news-august-2023).

**Comment by maelle** [comment]
I'm not forgetting this, I've added this to next week's list, so sorry about the delay!

**Comment by mfenner** [comment]
No problem. Have a nice weekend!

**Comment by maelle** [comment]
@mfenner https://ropensci.org/blog/index.json is now live :tada:

**Comment by mfenner** [comment]
@maelle Rogue Scholar switched to using https://ropensci.org/blog/index.json as feed URL. I have also enabled DOI registration, which is intentionally throttled at one DOI every 10 minutes, so the DOI registrations will take a few days, starting with the newest posts.

**Comment by mfenner** [comment]
I would suggest to register the Spanish and French feeds as separate feeds in Rogue Scholar. Is that ok? An will you also provide a feed in JSON Feed format?

Also, I have figured out a way to link to translated posts without too much technical overhead. And also content cross-posted somewhere else, which I think you frequently do. This information then goes into the DOI metadata.

**Comment by mfenner** [comment]
An example is this post https://doi.org/10.53731/ewrv712-2k7rx6d, also including funding information. The URLs of the cross-posted content and funding info (and also the references) are included in the DOI metadata:  https://api.crossref.org/works/10.53731/ewrv712-2k7rx6d

**Comment by maelle** [comment]
> Also, I have figured out a way to link to translated posts without too much technical overhead. And also content cross-posted somewhere else, which I think you frequently do. This information then goes into the DOI metadata.

What is needed on rOpenSci website end?

**Comment by mfenner** [comment]
@maelle sorry, I meant a JSON Feed for the Spanish and French posts (you shared RSS links).

**Comment by maelle** [comment]
oh sorry! I meant https://ropensci.org/fr/blog/index.json and https://ropensci.org/es/blog/index.json I'll try to submit them later this week. Thank you!

**Comment by mfenner** [comment]
@maelle thanks. I added the two versions of the blog to Rogue Scholar and linked them to your account: https://rogue-scholar.org/blogs/ropensci_es and https://rogue-scholar.org/blogs/ropensci_fr. There are some minor issues to address, please take a look when you find the time:

* `feed_url` and `favicon` in the JSON Feeds are broken. They should not use double slashes.
* Maybe you want to use a separate favicon for the three feeds. E.g. a favicon in a different color or with the words `es` or `fr` added
* the discussion of linking the different translations in the DOI metadata is a bigger topic. I suggest to take a similar approach as for links to cross-posted content, see https://github.com/ropensci/roweb3/issues/643.

**Pull request merged**
