### PR TITLE
Do not merge - testing comm call page

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@maelle Please see image for preview
- Can you please stop YAML `description:` from being displayed in the single comm call page? 
- I might want to use headings in text for summary of event, but these lovely link symbols appear

image

**Comment by stefaniebutland** [comment]
Sample zoom info, where the phone #'s shouldn't change between calls

```Stefanie Butland is inviting you to a scheduled Zoom meeting.

Topic: rOpenSci Community Call - Wild World of Data Repositories
Time: Dec 16, 2020 10:00 AM Pacific Time (US and Canada)

Join Zoom Meeting
https://zoom.us/j/92298909939?pwd=MERubjdNUUw2aWp6RUFqSHllR01adz09

Meeting ID: 922 9890 9939
Passcode: 896415
One tap mobile
+13462487799,,92298909939#,,,,,,0#,,896415# US (Houston)
+16468769923,,92298909939#,,,,,,0#,,896415# US (New York)

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 646 876 9923 US (New York)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington D.C)
        +1 312 626 6799 US (Chicago)
        +1 647 374 4685 Canada
        +1 647 558 0588 Canada
        +1 778 907 2071 Canada
        +1 204 272 7920 Canada
        +1 438 809 7799 Canada
        +1 587 328 1099 Canada
        +41 43 210 70 42 Switzerland
        +41 43 210 71 08 Switzerland
        +41 44 529 92 72 Switzerland
        +41 22 591 00 05 Switzerland
        +41 22 591 01 56 Switzerland
        +41 31 528 09 88 Switzerland
        +32 2 588 4188 Belgium
        +32 2 788 0172 Belgium
        +32 2 788 0173 Belgium
        +32 1579 5132 Belgium
        +32 2 290 9360 Belgium
        +32 2 585 5574 Belgium
        +61 3 7018 2005 Australia
        +61 7 3185 3730 Australia
        +61 8 6119 3900 Australia
        +61 8 7150 1149 Australia
        +61 2 8015 6011 Australia
Meeting ID: 922 9890 9939
Passcode: 896415
Find your local number: https://zoom.us/u/acNfrusD8

Join by SIP
92298909939@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
115.114.131.7 (India Mumbai)
115.114.115.7 (India Hyderabad)
213.19.144.110 (Amsterdam Netherlands)
213.244.140.110 (Germany)
103.122.166.55 (Australia)
149.137.40.110 (Singapore)
64.211.144.160 (Brazil)
69.174.57.160 (Canada)
207.226.132.110 (Japan)
Meeting ID: 922 9890 9939
Passcode: 896415
```

**Comment by maelle** [comment]
So what does change between calls?

**Comment by maelle** [comment]
Closing in favor of my own PR where I am trying to answer questions except for the ones we'll tackle on our call.

**Pull request closed without merging**
