### PR TITLE
footnotes

### LINKED ISSUE #7: Add tooltip when hovering over footnote numbers
Many rOpenSci blog posts include a lot of footnotes. Currently, to read the footnote text, you have to click on the number, which brings you to the bottom of the page. To go back, you have to click "previous page" on your browser or scroll up but in both cases, you lose where you were in text and it disrupts the reading flow. It would be more convenient if the footnote text appeared in a tooltip when the reader hovers over the footnote number.

I have no idea how idea difficult this would be so feel free to close if that's too much of a hassle.

### PR DESCRIPTION
**Pull request by maelle**
Fix #7 -- In the future if there is a Markdown render hook for footnotes, we can switch to using bootstrap for this.

PR in roweb3-styles adding the littlefoot npm package https://github.com/ropensci-org/roweb3-styles/pull/3 (to get the CSS)

### CODE REVIEW

**Comment by maelle** [comment]
:wave: @jeroen

**Review by stefaniebutland — COMMENTED** [review]
In the preview I don't see footnotes in a post whose live version has footnotes

- [preview](https://deploy-preview-97--ropensci.netlify.app/blog/2020/11/10/coronaviruses-and-hosts/)
- [live](https://ropensci.org/blog/2020/11/10/coronaviruses-and-hosts/)

**Comment by maelle** [comment]
With this they are accessible via the number (click) not at the bottom

Screenshot_20201130-200700

**Comment by maelle** [comment]
(Which you are free to dislike, and which might just not work in your browser?)

**Comment by stefaniebutland** [comment]
ah! Works for me in Chrome Version 87.0.4280.67 (Official Build) (x86_64)

It's great to see the footnote/ citation without going to bottom of post.

However, as with journal articles, I like to see the citations (aka footnotes here) listed at the bottom of the post. Is it easily possible to have both or should we choose?

**Comment by maelle** [comment]
At least if we use littlefoot.js we need to choose (I've just checked its docs).

**Comment by maelle** [comment]
but we could use something else, in distill blogs you get both.

**Comment by jeroen** [comment]
I don't really like this. For example I had a little foot note on: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

But with the new plugin this turns into a popup that isn't even the right size: https://deploy-preview-97--ropensci.netlify.app/technotes/2020/11/19/moving-away-travis/

I don't agree that popups result in a better "flow" than footnotes. I prefer not to introduce new widgets.

**Comment by jeroen** [comment]
Also the problem with these widgets is that the popups start to overlap on mobile:

Screenshot_20201208-122442

**Pull request closed without merging**
