### PR TITLE
try

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
the anchor is still in RSS feeds but it's small. See https://codebeautify.org/rssviewer with the preview for /rbloggers/index.xml

**Comment by maelle** [comment]
the width and height could also be 0 and re-added on our side via CSS but it's getting very hacky

**Comment by maelle** [comment]
👋 @jeroen

**Comment by jeroen** [comment]
lgtm for now, but I'd still like to find a better fix at some point.

**Comment by maelle** [comment]
How about we merge but keep the issue open?

**Comment by jeroen** [comment]
Yes, that sounds good.

**Pull request merged**
