### PR TITLE
yfR blog post

### PR DESCRIPTION
**Pull request by msperlin**
Following [software review](https://github.com/ropensci/software-review/issues/523), this PR adds my blog post about yfR.

### CODE REVIEW

**Comment by msperlin** [comment]
@steffilazerte

**Comment by msperlin** [comment]
But I'm not able to add reviewers... perhaps I don't have the permissions?

**Comment by steffilazerte** [comment]
That's great @msperlin! 

Could you add the author's checklist to your PR so I don't have to bug you about the small stuff :wink: 
You can find it in the [Appendix](https://blogguide.ropensci.org/authorchecklistpeer.html) of the [Blog Guide](https://blogguide.ropensci.org/)

**Comment by msperlin** [comment]
@steffilazerte Sure, I'll do that today or tomorrow.

**Pull request closed without merging**
